language: ruby

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.8.0

before_install:
  - docker version
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose version
  - cp docker-compose.local.travis.yml docker-compose.local.yml

install:
  - docker build -t savaslabs/squabble:latest .
  - make install
  - composer install
  - docker exec squabble_web_1 chmod ugo+rw /var/www/html/storage/logs/lumen.log

script:
  - docker exec squabble_web_1 phpunit
  - vendor/bin/behat -v
  - docker exec squabble_web_1 cat /var/log/nginx/access-squabble.log
  - docker exec squabble_web_1 cat /var/log/nginx/error-squabble.log
