language: ruby

services:
  - docker

before_install:
  - docker version
  - docker-compose version
  - cp docker-compose.local.travis.yml docker-compose.local.yml

install:
  - make install

script:
  - make test

after_failure:
  - docker logs squabble_app_1
