version: '2'
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - /etc/nginx/conf.d
  dockergen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./docker/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
  app:
    build: .
    environment:
      - VIRTUAL_HOST=local.comments.savaslabs.com
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=abracadabra
      - CACHE_DRIVER=file
      - SESSION_DRIVER=file
      - APP_LOCALE=en
      - APP_FALLBACK_LOCALE=en
      - DB_CONNECTION=sqlite
      - DB_HOST=localhost
      - NOCAPTCHA=owl
      - MAIL_DRIVER=log
      - BASEURL=localhost:8000
      - DB_DATABASE=/db/database.sqlite
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - DAC_OVERRIDE
      - SETGID
      - SETUID
    volumes:
        - db:/db
        - vendor:/var/www/html/vendor

volumes:
  db:
    driver: local
  vendor:
    driver: local
