version: '2'
services:
  web:
    image: savaslabs/squabble:latest
    restart: always
    ports:
      - "80:80"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - CACHE_DRIVER=file
      - SESSION_DRIVER=file
      - APP_LOCALE=en
      - APP_FALLBACK_LOCALE=en
      - DB_CONNECTION=sqlite
      - DB_HOST=localhost
      - DB_DATABASE=/db/database.sqlite
      - NOCAPTCHA=owl
      - MAIL_DRIVER=smtp
      - MAIL_HOST=fill-this-in
      - MAIL_FROM_ADDRESS="fill-this-in"
      - MAIL_FROM_NAME=fill-this-in
      - MAIL_USERNAME=fill-this-in
      - MAIL_PASSWORD=fill-this-in
      - BASEURL=fill-this-in
      - APP_KEY=secret
      - SLACK_WEBHOOK_URL=secret
      - MANDRILL_KEY=secret
    volumes:
      - /db:/db
      - /logs:/var/www/html/storage/logs
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - NET_BIND_SERVICE
      - SETGID
      - SETUID
